### ISSUE TITLE
Support for installs without GCC using PYMMH3?

### ISSUE THREAD

**Issue by jacobertel** [thingsboard/thingsboard-python-client-sdk#35]
Hello,
I was trying to install this library on an Inhand Networks IG502 IOT gateway. The device provides capability for users to run and execute python and python libraries, and no more. It does not seem possible to run packages with C dependencies. Is it possible the code could be updated to switch to PYMMH3 if MMH3 install fails? Obviously this would impact performance if GCC is not available. I am using this gateway more like a sensor node, and expect it to send a telemetry update at most once a minute. High performance is not applicable in my use case.

Thank you for your consideration.

**Comment by samson0v** [comment]
@jacobertel, done in https://github.com/thingsboard/thingsboard-python-client-sdk/commit/7b1ffcc2cdcaa6ee4073f5feaf3085dd59ee84b2
