### ISSUE TITLE
AttributeError: 'TBGatewayMqttClient' object has no attribute '_TBGatewayMqttClient__attrs_request_timeout'. Did you mean: '_TBDeviceMqttClient__attrs_request_timeout'?

### ISSUE THREAD

**Issue by MohamedKHALILRouissi** [thingsboard/thingsboard-python-client-sdk#76]
File "/home/khalil/test-2/test/lib/python3.11/site-packages/tb_gateway_mqtt.py", line 178, in __request_attributes
    self.__attrs_request_timeout[attr_request_number] = int(time()) + 20
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TBGatewayMqttClient' object has no attribute '_TBGatewayMqttClient__attrs_request_timeout'. Did you mean: '_TBDeviceMqttClient__attrs_request_timeout'?

**Comment by khalilKian** [comment]
pull request:
https://github.com/thingsboard/thingsboard-python-client-sdk/pull/77
